name: kanban_board
description: Customizable & draggable Kanban Board widget for Flutter. Build Trello-like task boards with smooth drag-and-drop and flexible task management.
version: 1.0.0+2
homepage: https://github.com/1akhanBaheti/FlutterKanbanBoard

environment:
  sdk: '>=2.19.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  dotted_border: ^2.1.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
